/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import java.util.*; //IMPORTADA OS PACOTES DO JAVA.UTIL

/**
 *
 * @author dougl
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }
    
    ArrayList<String> palavras = new ArrayList<>(); //ARRAY CRIADA JUNTO A CRIAÇÃO DE UMA NOVA FORMA DO GAME!!!
    //ASSIM ELA PODE SER ACESSADA EM TODO ESCOPO DO ALGORITMO!!!
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdLetra = new javax.swing.JTextField();
        javax.swing.JButton btnTentar = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jblPalavra = new javax.swing.JLabel();
        jblVidas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jblGanhou = new javax.swing.JLabel();
        tfdForca = new javax.swing.JLabel();
        jlbPerdeu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jlbMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfdLetra.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTentar.setText("Tentar Letra!");
        btnTentar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentarActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        btnStart.setForeground(new java.awt.Color(153, 153, 0));
        btnStart.setText("START!");
        btnStart.setAlignmentY(0.0F);
        btnStart.setBorder(null);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jblPalavra.setFont(new java.awt.Font("Amiri Quran", 0, 3)); // NOI18N
        jblPalavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jblVidas.setFont(new java.awt.Font("Source Code Pro Medium", 1, 48)); // NOI18N
        jblVidas.setForeground(new java.awt.Color(255, 102, 0));
        jblVidas.setText("4");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        jLabel3.setText("VIDAS=>");

        jblGanhou.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N

        tfdForca.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 36)); // NOI18N

        jlbPerdeu.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Noto Serif Cond", 3, 36)); // NOI18N
        jLabel1.setText("JOGO DA FORCA=>");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Liberation Mono", 2, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 153, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Projeto de Java \nde um Jogo da Forca\nSimples. As palavras\nja estão gravadas no \nalgoritmo, é só\ndar START e curtir!");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Descubra esta palavra! -->");

        jlbMostrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbMostrar.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(603, 603, 603)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblVidas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPerdeu, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jblGanhou, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(tfdLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnTentar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfdForca, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jblPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jlbMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jblPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jblVidas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39)))
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdForca, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jblGanhou, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTentar)
                            .addComponent(tfdLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlbPerdeu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentarActionPerformed
        // TODO add your handling code here: //ESTAVA COM DIFICULDADES DE OBTER ESSE DADO APÓS O BOTÃO INICIAR JOGO, POIS OS EVENTOS SÃO PRIVADOS ENTÃO...        
        if (tfdForca.getText().isEmpty() && tfdLetra.getText().isEmpty()){ //CONDICIONAL AND NO COMANDO IF É &&
            jblGanhou.setText("Aperte START!!!");
        }        
        if (tfdLetra.getText().isEmpty() != tfdForca.getText().isEmpty()){ //CUIDAR ESSAS CONDIÇÕES IF, POIS MUDA DO ELSE IF!!!
            jblGanhou.setText("Digite uma letra!");            
            tfdLetra.requestFocus();
        }        
              
        char[] palavra = jblPalavra.getText().toCharArray(); //UMA MANEIRA DE OBTER O DADO DA PALAVRA SEM COMEÇAR DE NOVO FOI CAPTURAR ESSE DADO DO LABEL ADICIONAL CRIADO NO PAINEL DA INTERFACE!!!
        String secreto = tfdForca.getText();
        //USADO UM TIPO DIFERENTE DE CLASSE CHAMADA STRING BUILDER, PERMITE MANIPULAR UM TIPO STRING
        StringBuilder adivinha = new StringBuilder(secreto); //É PASSADO COMO PARÂMETRO PARA A CLASSE USAR A STRING SECRETO PARA MANIPULAÇÃO DESSE DADO!!!
        char letra = tfdLetra.getText().toUpperCase().charAt(0);
        tfdLetra.setText("");
        tfdLetra.requestFocus();
        
        boolean achou = false;
        int vidas = Integer.parseInt(jblVidas.getText());
        
        for(int i=0; i<palavra.length; i++){
            if(palavra[i] == letra){
                adivinha.setCharAt(i, letra); //AQUI É USADO UM MÉTODO DO STRING BUILDER QUE PERMITE ESSE PROCESSO!!!
                tfdForca.setText(adivinha.toString());
                achou = true; //ACHOU ENTÃO RECEBE TRUE
                jblGanhou.setText("Acertou! Tente de novo");
                tfdLetra.requestFocus();
            }
        }            
            if (achou == false != tfdForca.getText().isEmpty()){
            achou = false;
            vidas --;
            jblVidas.setText(Integer.toString(vidas)); //USAMOS ESSAS CONVERSÕES PORQUE ESSES BOTÕES RECEBEM STRINGS E NÃO INTEIROS!!!
            jblGanhou.setText("Errou! Tente novamente");
            tfdLetra.requestFocus();
            }
       
            if (jblPalavra.getText().equals(tfdForca.getText()) != (tfdForca.getText().isEmpty())){
            jblGanhou.setText("Parabéns!!!");
            jblPalavra.setText("");
            jblVidas.setText(" :-D ");
            tfdForca.setText("");
            tfdLetra.setText("");
        }  
            if (vidas == 0){                
                jblVidas.setText(" X-D ");
                tfdForca.setText("");
                tfdLetra.setText(""); 
                jlbPerdeu.setText("PERDEU! JOGUE NOVAMENTE!!!");
                jblGanhou.setText("");
                jlbMostrar.setText("A palavra era: " + jblPalavra.getText());
                jblPalavra.setText("");            
            }
    }//GEN-LAST:event_btnTentarActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        palavras.add("LEITURA");
        palavras.add("GAME");
        palavras.add("ANALISE");
        palavras.add("DIVERTIDO");
        palavras.add("ESTUDANDO");
        palavras.add("JOYSTICK");
        jblVidas.setText("4");
        jblGanhou.setText("");
        jlbMostrar.setText("");
        int p = palavras.size();
        Random aleatorio = new Random();
        int opcao = aleatorio.nextInt(p); //USANDO O MÉTODO NEXTINT() ELE GERA UM NÚMERO INTEIRO
        jblPalavra.setText(palavras.get(opcao));
        
        char[] palavra = jblPalavra.getText().toCharArray(); //CRIADO VETOR DO TIPO CHAR
        String secreto = ""; //É MOSTRADO UM SINAL ! QUANDO VARIAVEIS NÃO ESTAO SENDO USADAS TAMBÉM PARA CUIDAR O USO DE RECURSOS!!!
        for(int i=0; i<palavra.length; i++){
            secreto = secreto + "*";
        }
        tfdForca.setText(secreto);
        jlbPerdeu.setText(""); 
        tfdLetra.requestFocus();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel jblGanhou;
    public javax.swing.JLabel jblPalavra;
    public javax.swing.JLabel jblVidas;
    private javax.swing.JLabel jlbMostrar;
    public javax.swing.JLabel jlbPerdeu;
    public javax.swing.JLabel tfdForca;
    public javax.swing.JTextField tfdLetra;
    // End of variables declaration//GEN-END:variables
}
