mensagem="Meu Primeiro Script!!!"; //CRIAMOS UMA STRING COM NOME MENSAGEM E MANDAMOS DIZER O QUE ESTÁ ESCRITO DENTRO, UMA STRING!!!//
alert(mensagem); //O JAVASCRIPT É UMA LINGUAGEM COM TIPAGEM FRACA!!!
